[[constraint]]
  name = "github.com/Azure/azure-pipeline-go"
  version = "0.1.8"

[[constraint]]
  name = "github.com/Azure/azure-storage-blob-go"
  version = "0.3.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.16.7"

[[constraint]]
  name = "github.com/djherbis/buffer"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "gopkg.in/djherbis/nio.v2"
  version = "2.0.3"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.0"

[[constraint]]
  branch = "release-1.13"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "10.0.0"

[prune]
  go-tests = true
  unused-packages = true
